#!/usr/bin/env python
import os
import sys

if 'OPENSHIFT_REPO_DIR' in os.environ:    #Py3
    ON_OPENSHIFT = True
else:
    ON_OPENSHIFT = False

if ON_OPENSHIFT:
    os.environ['DJANGO_SETTINGS_MODULE'] = 'maplite.settings'
    sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi', 'maplite'))

    virtenv = os.environ['OPENSHIFT_PYTHON_DIR'] + '/virtenv/venv/'
    os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python3.3/site-packages')

    virtualenv = os.path.join(virtenv, 'bin/activate_this.py')

    try:
        exec(compile(open(virtualenv).read(), virtualenv, 'exec'),	#Py3
            dict(__file__ = virtualenv) )
    except IOError:
        pass
else:				#This else solve the OUCH! things
    os.environ['DJANGO_SETTINGS_MODULE'] = 'maplite.settings'
    sys.path.append('/home/endik/Documents/WorkSpace/Python/endikApp/VENV/OPENSHIFT/mapp/wsgi/maplite')

#
# IMPORTANT: Put any additional includes below this line.  If placed above this
# line, it's possible required libraries won't be in your searchable path
# 

import django.core.handlers.wsgi		#OUCH!
application = django.core.handlers.wsgi.WSGIHandler()
